### ISSUE TITLE
Encontrar até 3 glossários de obras (eng. civil)

### ISSUE THREAD

**Issue by masmangan** [masmangan/verbose-memory#4]
Procurar no Ministério do Trabalho as profissões relacionadas.
Procurar elementos e detalhamentos.
Procurar no SGSP a lista de materiais/insumos.
Procurar a lista de ocorrências.
Procurar a lista de equipamentos.

**Comment by PvMeira** [comment]
link de glossario
http://www.ebah.com.br/content/ABAAAAg5cAE/glossario-construcao-civil

**Comment by ManoelaR** [comment]
Link de glossário
http://www.ibape-sp.org.br/arquivos/glossario_de_terminologia.pdf

**Comment by masmangan** [comment]
@PvMeira @ManoelaR utilizem a wiki para registrar as referências.

**Comment by ManoelaR** [comment]
@masmangan Referências adicionadas na Wiki.
