### ISSUE TITLE
Detalhar cenário de caso de uso: Revisar diário de obras

### ISSUE THREAD

**Issue by masmangan** [masmangan/verbose-memory#5]

**Comment by CelsoLJunior** [comment]
OPW.zip adicionado na pasta docs.

Exemplo da tela.

**Comment by masmangan** [comment]
@CelsoLJunior ao fazer o commit, utilize o número do incidente.

**Comment by masmangan** [comment]
@CelsoLJunior @Iljuszyk alterar tela para permitir aprovar ou reprovar RDO.
Apresentar tela com RDO em formato de texto, com botões aprovar e reprovar, com campo de comentário.
Atualizar diagrama de classes de análise.
Completar casos de teste e caso de uso.
