### ISSUE TITLE
Detalhar cenário de caso de uso: Preencher diário de obras

### ISSUE THREAD

**Issue by masmangan** [masmangan/verbose-memory#6]

**Comment by GuillermoAlonsoLima** [comment]
[Preencher Diario de Obras.docx](https://github.com/masmangan/verbose-memory/files/341544/Preencher.Diario.de.Obras.docx)
Descrição do Caso de Uso Preencher Diario de Obras.
Perguntas:
Deveria retirar os titulos inecessários?
O que são os steps(passos) no key scenarios?

**Comment by HelemSilva** [comment]
https://drive.google.com/open?id=0B8lCLx5HDxtsOExRSmN2WmNNTXM
Tela (preencher dados do diário de obra)

**Comment by masmangan** [comment]
@GuillermoAlonsoLima utilizar o git para incluir arquivos no projeto.

**Comment by masmangan** [comment]
@GuillermoAlonsoLima @HelemSilva completar entidades na classe de análise de acordo com tela.
Criar dados de teste e descrição de caso de uso.
Atualizar diagrama de análise.
