### ISSUE TITLE
Detalhar cenário de caso de uso: Informar cotações

### ISSUE THREAD

**Issue by masmangan** [masmangan/verbose-memory#7]

**Comment by masmangan** [comment]
@telesca95 @PvMeira Como está o andamento da tarefa?

**Comment by PvMeira** [comment]
Tela completa

**Comment by masmangan** [comment]
@PvMeira colocar unidade (quilo, metro, lata)
Completar dados de teste, descrição de caso de uso e revisar classes de análise.

**Comment by masmangan** [comment]
@PvMeira gerar nova tela em formato de imagem.
