### ISSUE TITLE
Detalhar requisitos do sistema

### ISSUE THREAD

**Issue by masmangan** [masmangan/verbose-memory#8]

**Comment by ManoelaR** [comment]
Adicionado Requisitos de Sistema em formato docx.

**Comment by ManoelaR** [comment]
[OPW_Requisitos_Sistema.docx](https://github.com/masmangan/verbose-memory/files/342622/OPW_Requisitos_Sistema.docx)

**Comment by masmangan** [comment]
@ManoelaR utilize o git para incluir arquivos no projeto.

**Comment by masmangan** [comment]
@YuriWMartins desenvolver o documento atual.
