### ISSUE TITLE
Decidir pela plataforma do sistema

### ISSUE THREAD

**Issue by masmangan** [masmangan/verbose-memory#9]
Alternativas:
Android
Web
Desktop Swing
Desktop JavaFX

**Comment by HelemSilva** [comment]
Web

**Comment by Iljuszyk** [comment]
web php , java script

**Comment by PvMeira** [comment]
WEB- Java JSF

**Comment by CelsoLJunior** [comment]
Web Java

**Comment by YuriWMartins** [comment]
Web Java

**Comment by GuillermoAlonsoLima** [comment]
Web Javascript php

**Comment by masmangan** [comment]
Para continuar em Web, considerar as seguintes aplicações de exemplo:
- https://github.com/phasenraum2010/javaee7-petclinic
- https://github.com/phasenraum2010/phppetclinic

**Comment by masmangan** [comment]
https://github.com/spring-projects/spring-petclinic

**Comment by masmangan** [comment]
@YuriWMartins Atualizar documento de requisitos de sistema na próxima iteração.

**Comment by PvMeira** [comment]
Angular.js & Spring https://github.com/sigfridoprez/spring-petclinic-angularjs
